import { SubmissionResult } from './judge0Client';

export interface ParsedExecutionResult {
  status: string;
  output: string;
  expectedOutput?: string;
  passed: boolean;
  time: number;
  memory: number;
  error?: string;
}

export const parseJudge0Result = (result: SubmissionResult, expectedOutput?: string): ParsedExecutionResult => {
  const statusId = result.status.id;
  const description = result.status.description;

  const time = parseFloat(result.time || '0') * 1000; // Convert to ms
  const memory = result.memory || 0; // KB

  // Handle Compilation Error (ID 6)
  if (statusId === 6) {
    return {
      status: 'Compilation Error',
      output: '',
      passed: false,
      time,
      memory,
      error: result.compile_output || 'Unknown compilation error'
    };
  }

  // Handle Runtime Errors (IDs 7-12)
  if (statusId >= 7 && statusId <= 12) {
    return {
      status: 'Runtime Error',
      output: result.stdout || '',
      passed: false,
      time,
      memory,
      error: result.stderr || result.message || description
    };
  }

  // Handle Time Limit Exceeded (ID 5)
  if (statusId === 5) {
    return {
      status: 'Time Limit Exceeded',
      output: result.stdout || '',
      passed: false,
      time,
      memory
    };
  }

  // Handle Accepted (ID 3)
  if (statusId === 3) {
    const output = (result.stdout || '').trim();
    const expected = (expectedOutput || '').trim();
    
    // If expected output is provided, we double check it just in case,
    // though Judge0 handles it if expected_output was sent in the request.
    const passed = expected === '' || output === expected;

    return {
      status: passed ? 'Accepted' : 'Wrong Answer',
      output,
      expectedOutput: expected,
      passed,
      time,
      memory
    };
  }

  // Fallback for Wrong Answer (ID 4 is MLE, but usually WA is generated by Judge0 when expected_output doesn't match)
  // Actually, Judge0 WA ID is 4? No, ID 4 is MLE. ID 14 is WA? Wait, Judge0 WA is ID 4?
  // Let's rely on passed property or status description.
  // Standard Judge0 statuses: 3=Accepted, 4=Wrong Answer, 5=TLE, 6=CE, 7..12=RE.
  // Wait, let's correct standard Judge0 IDs:
  // 3: Accepted
  // 4: Wrong Answer
  // 5: Time Limit Exceeded
  // 6: Compilation Error
  // 7-12: Runtime Error (SIGSEGV, SIGXFSZ, SIGFPE, SIGABRT, NZEC, Other)
  // 13: Internal Error
  // 14: Exec Format Error
  if (statusId === 4) {
    return {
      status: 'Wrong Answer',
      output: (result.stdout || '').trim(),
      expectedOutput: (expectedOutput || '').trim(),
      passed: false,
      time,
      memory
    };
  }

  return {
    status: description,
    output: result.stdout || '',
    passed: false,
    time,
    memory,
    error: result.stderr || undefined
  };
};
